### ISSUE TITLE
Can you add more options?

### ISSUE THREAD

**Issue by spazbg** [MilindPurswani/whoxyrm#1]
Great tool, but can you add more options?

**Comment by MilindPurswani** [comment]
Hi,

Do you have any specific options in mind? This tool is intended to leverage the Whoxy Reverse Micro API(and thus the name whoxyrm). Nonetheless, I can add a few or probably create another one if needed. 

Thanks

**Comment by spazbg** [comment]
I am asking for the other API options like "owner's name", "email address", "domain keyword"

**Comment by MilindPurswani** [comment]
Thanks for suggestion.

Since whoxy provides built-in [API](https://www.whoxy.com/reverse-whois/), I think this should be relatively easy to implement. I'll start working on this right away. :)

**Comment by spazbg** [comment]
That's my point :)

**Comment by MilindPurswani** [comment]
I just sent out a commit to the test branch @spazbg. Can you please check and confirm if this works according to your needs before I merge it to master branch?

Thanks,

**Comment by tibug** [comment]
Hello how I can add api key ?

**Comment by MilindPurswani** [comment]
Marking as resolved.

Thanks,

Milind
