### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by GDATTACKER-RESEARCHER** [MilindPurswani/whoxyrm#4]
2022/08/04 19:12:17 json: cannot unmarshal string into Go struct field ResponseStruct.total_results of type int
2022/08/04 19:12:17 json: cannot unmarshal string into Go struct field ResponseStruct.total_results of type int
2022/08/04 19:12:18 json: cannot unmarshal string into Go struct field ResponseStruct.total_results of type int
2022/08/04 19:12:18 json: cannot unmarshal string into Go struct field ResponseStruct.total_results of type int
2022/08/04 19:12:19 json: cannot unmarshal string into Go struct field ResponseStruct.total_results of type int

**Comment by sa1tama0-ctrl** [comment]
same problem

**Comment by hakluke** [comment]
+1

**Comment by MilindPurswani** [comment]
Hey there, 

Thanks for raising this issue and apologies for responding late. I am currently occupied with some other stuff and probably won’t be able to look at this one for a while. I am accepting PRs though. If you think you have a quick fix, feel free to raise one. 

Thanks!

**Comment by Amnotacat** [comment]
+2

**Comment by MilindPurswani** [comment]
This should be fixed now. Thanks for using whoxyrm.

**Comment by GDATTACKER-RESEARCHER** [comment]
> This should be fixed now. Thanks for using whoxyrm.

thanks alot bro will verify it

**Comment by Amnotacat** [comment]
looks good @MilindPurswani thanks.
