### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by c4ir0** [MilindPurswani/whoxyrm#6]
Do I miss sth, bro ? 

![321](https://user-images.githubusercontent.com/108268587/193428403-213554f9-480e-461d-bd7c-a3a3f75cb1df.JPG)

![123](https://user-images.githubusercontent.com/108268587/193428356-7c07e69d-a6ae-4612-b9e1-82d55b6c6b5a.JPG)

**Comment by Ashley-Pursell** [comment]
i got this issue aswell did u find a fix?

**Comment by c4ir0** [comment]
> i got this issue aswell did u find a fix?

No

**Comment by MilindPurswani** [comment]
Hi, 

Thanks for raising this issue. I'll take a look at this and try to get this fixed as soon as possible. Meanwhile, if you find a root cause behind this, I am accepting PRs. Feel free to raise one. 

Thanks, 
Milind

**Comment by sushantdhopat** [comment]
same not getting any result

**Comment by WarrDaddy** [comment]
Same issue here

**Comment by sidxparab** [comment]
@c4ir0 Try inserting double quotes around your key like:

`export WHOXY_API_KEY="79acb1f557df3237l17c769"`

For me the tool is working fine!

**Comment by MilindPurswani** [comment]
As highlighted by @sidxparab, please add double quotes around the API key, and it should work. However, I have not been able to reproduce this issue. 

```
$ export WHOXY_API_KEY="..."
```

Feel free to open a new issue incase the problem persists.
